try{if(JSON.parse(atob(localStorage.getItem('nexora_token').split('.')[1])).exp*1000<=Date.now())throw new Error('expired')}catch{localStorage.removeItem('nexora_token');localStorage.removeItem('nexora_user');location.replace('index.html')}
const q=selector=>document.querySelector(selector),qa=selector=>[...document.querySelectorAll(selector)];
let zoom=1,chartMode='line',lastHit=0,marketIndex=3,digitCursor=0;
let points=Array.from({length:120},(_,i)=>500+Math.sin(i/7)*70+(Math.random()-.5)*75),digits=Array.from({length:10},(_,n)=>({n,p:8.2+Math.random()*3.1,next:Date.now()+n*310}));
const marketNames=['Volatility 10 (1s)','Volatility 25 (1s)','Volatility 50 (1s)','Volatility 75 (1s)','Volatility 100 (1s)','Volatility 150','Volatility 200','Volatility 250','Volatility 300','Volatility 500'];
const profiles=[[1.05,.92,1.10,.96,1.02,.88,1.08,.94,1.01,.98],[.94,1.07,.96,1.11,.91,1.04,1.08,.93,1.03,.99],[1.10,.89,1.03,.95,1.08,.92,1.12,.87,1.01,1.03],[.90,1.12,.95,1.04,.88,1.09,.97,1.06,.92,1.07],[1.08,.96,.91,1.10,1.02,.87,1.11,.94,1.06,.95],[.93,1.09,1.04,.90,1.12,.96,1.01,.88,1.07,.99],[1.11,.91,1.06,.95,.89,1.10,.97,1.04,.92,1.05],[.96,1.08,.90,1.12,1.02,.94,1.09,.87,1.05,.97],[1.04,.88,1.11,.93,1.07,.96,.90,1.12,.95,1.03],[.89,1.10,.94,1.06,.92,1.11,.98,.90,1.08,.96]];
q('#marketList').innerHTML=marketNames.map(name=>`<button>${name}</button>`).join('');
q('#marketToggle').onclick=()=>q('#marketList').classList.toggle('open');qa('#marketList button').forEach((button,index)=>button.onclick=()=>{marketIndex=index;q('#instrumentName').textContent=button.textContent;q('#marketList').classList.remove('open');toast(`${button.textContent} selected`);});
function yFor(point,height){return height*.5-(point-500)*zoom;}
function drawLine(ctx,box){const base=box.height*.5;ctx.save();ctx.setLineDash([4,5]);ctx.strokeStyle='#7890b533';ctx.beginPath();ctx.moveTo(0,base);ctx.lineTo(box.width,base);ctx.stroke();ctx.restore();for(let i=1;i<points.length;i++){const previous=points[i-1],current=points[i],x1=(i-1)*box.width/(points.length-1),x2=i*box.width/(points.length-1);ctx.strokeStyle=current>=previous?'#28d8a2':'#ff667b';ctx.lineWidth=2.6;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=7;ctx.beginPath();ctx.moveTo(x1,yFor(previous,box.height));ctx.lineTo(x2,yFor(current,box.height));ctx.stroke();}ctx.shadowBlur=0;}
function drawCandles(ctx,box){const step=box.width/Math.min(points.length,60);for(let i=1;i<points.length;i+=2){const open=points[i-1],close=points[i],high=Math.max(open,close)+Math.random()*18,low=Math.min(open,close)-Math.random()*18,x=i*box.width/(points.length-1),green=close>=open,color=green?'#2ce0b0':'#ff6078';ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=1.2;ctx.shadowColor=color;ctx.shadowBlur=5;ctx.beginPath();ctx.moveTo(x,yFor(high,box.height));ctx.lineTo(x,yFor(low,box.height));ctx.stroke();const top=yFor(Math.max(open,close),box.height),height=Math.max(2,Math.abs(yFor(open,box.height)-yFor(close,box.height)));ctx.fillRect(x-step*.35,top,step*.7,height);}ctx.shadowBlur=0;}
function draw(){const canvas=q('#line'),box=canvas.getBoundingClientRect(),dpr=devicePixelRatio,ctx=canvas.getContext('2d');canvas.width=box.width*dpr;canvas.height=box.height*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,box.width,box.height);ctx.strokeStyle='#263551';ctx.lineWidth=1;for(let i=0;i<7;i++){ctx.beginPath();ctx.moveTo(0,i*box.height/7);ctx.lineTo(box.width,i*box.height/7);ctx.stroke();}chartMode==='line'?drawLine(ctx,box):drawCandles(ctx,box);}
function createDigits(){q('#digitList').innerHTML=digits.map(d=>`<div class="digit" data-n="${d.n}">${d.n}<small></small></div>`).join('');updateDigitDisplay();}
function updateDigitDisplay(){digits.forEach(d=>{const item=q(`[data-n="${d.n}"]`);if(!item)return;item.classList.toggle('green',d.p>=10);item.classList.toggle('red',d.p<10);item.querySelector('small').textContent=`${d.p.toFixed(2)}%`;});const active=q(`[data-n="${lastHit}"]`),host=q('#digitList');if(active&&host){const a=active.getBoundingClientRect(),h=host.getBoundingClientRect();q('#digitArrow').style.left=`${a.left-h.left+a.width/2-7}px`;}const even=digits.filter(x=>x.n%2===0).reduce((sum,x)=>sum+x.p,0),odd=digits.filter(x=>x.n%2).reduce((sum,x)=>sum+x.p,0);q('#evenP')&&(q('#evenP').textContent=`${even.toFixed(2)}%`);q('#oddP')&&(q('#oddP').textContent=`${odd.toFixed(2)}%`);}
function updateOneDigit(now){const digit=digits[digitCursor];if(now<digit.next)return;const target=8.1+profiles[marketIndex][digit.n]*1.75;digit.p=Math.max(6.2,Math.min(12,Number((digit.p+(target-digit.p)*.32+(Math.random()-.5)*.38).toFixed(2))));digit.next=now+800+Math.floor(Math.random()*2600);digitCursor=(digitCursor+1)%digits.length;}
function weightedHit(){const weights=profiles[marketIndex].map((weight,index)=>weight*(.75+digits[index].p/12));let total=weights.reduce((sum,value)=>sum+value,0),roll=Math.random()*total;for(let i=0;i<weights.length;i++){roll-=weights[i];if(roll<=0)return i;}return 9;}
function tick(){const now=Date.now();updateOneDigit(now);lastHit=weightedHit();window.nexoraLastDigit=lastHit;const pulse=(profiles[marketIndex][lastHit]-1)*16+(Math.random()-.5)*28;points.push(points.at(-1)+pulse);points=points.slice(-120);const change=(Math.abs(pulse)/5).toFixed(2),up=pulse>=0;q('#quoteLine').innerHTML=`${(9300+points.at(-1)/10).toFixed(2)} <i style="color:${up?'#10cf8b':'#ff4f67'}">${up?'+':'-'}${change}% ${up?'↑':'↓'}</i>`;draw();updateDigitDisplay();document.dispatchEvent(new CustomEvent('nexora:digit-hit',{detail:{digit:lastHit,market:marketNames[marketIndex]}}));}
function updateStake(){const stake=Math.max(1,Number(q('#stake').value)||1);q('#stake').value=stake;q('#payout').innerHTML=`${(stake*1.92).toFixed(2)} <small>USD</small>`;qa('.quick button').forEach(button=>button.classList.toggle('active',Number(button.textContent.slice(1))===stake));}
function toast(text){q('#toast').textContent=text;q('#toast').classList.add('show');clearTimeout(window.binaryToast);window.binaryToast=setTimeout(()=>q('#toast').classList.remove('show'),2200)}
q('#lineMode').onclick=()=>{chartMode='line';q('#lineMode').classList.add('active');q('#candleMode').classList.remove('active');draw()};q('#candleMode').onclick=()=>{chartMode='candles';q('#candleMode').classList.add('active');q('#lineMode').classList.remove('active');draw()};q('#zoomIn').onclick=()=>{zoom=Math.min(2,zoom+.15);draw()};q('#zoomOut').onclick=()=>{zoom=Math.max(.35,zoom-.15);draw()};q('#zoomReset').onclick=()=>{zoom=1;draw()};q('.x').onclick=()=>{q('#shade').classList.remove('open');q('#binModal').classList.remove('open')};window.addEventListener('resize',()=>{draw();updateDigitDisplay();});createDigits();draw();tick();setInterval(tick,1000);window.addEventListener('pagehide',()=>{if(sessionStorage.getItem('nexora_internal_navigation')==='settings'){sessionStorage.removeItem('nexora_internal_navigation');return}localStorage.removeItem('nexora_token');localStorage.removeItem('nexora_user')});
[['binary-enhancements.css','link'],['binary-housika.js','script'],['binary-mobile-trade.css','link'],['binary-elite.css','link'],['binary-extras.css','link'],['binary-enhancements.js','script'],['binary-trading.js','script'],['binary-ai.js','script'],['binary-risk.js','script'],['binary-wallet.css','link'],['binary-wallet.js','script'],['binary-responsive.css','link']].forEach(([src,type])=>{const asset=document.createElement(type);if(type==='link'){asset.rel='stylesheet';asset.href=src}else{asset.async=false;asset.src=src}document[type==='link'?'head':'body'].append(asset)});
