const ai$ = selector => document.querySelector(selector);
const aiMarkets = ['Volatility 10 (1s)','Volatility 25 (1s)','Volatility 50 (1s)','Volatility 75 (1s)','Volatility 100 (1s)','Volatility 10','Volatility 25','Volatility 50','Volatility 75','Volatility 100'];
document.body.insertAdjacentHTML('beforeend', '<section class="ai-dock" id="aiDock"><button class="ai-orb" id="aiScan">✦</button><div class="ai-copy"><small>NEXORA AI SCANNER</small><b id="aiPick">Scanning volatility activity…</b><span id="aiMeta">Live pattern scan · demo guidance only</span></div><button class="ai-go" id="aiGo">View</button></section><section class="ai-sheet" id="aiSheet"><header><div><small>NEXORA AI SCANNER</small><h2>Volatility activity map</h2></div><button id="aiClose">×</button></header><p>Ranks simulated volatility activity for workspace exploration. It is not a prediction or investment advice.</p><div id="aiRanks" class="ai-ranks"></div><div class="ai-tools"><button data-ai="watch">★ Watchlist</button><button data-ai="alert">◉ Smart alert</button><button data-ai="journal">▤ Trade note</button><button data-ai="focus">▣ Focus chart</button></div></section><div class="fx-layer" id="fxLayer"></div>');
let aiResult = null, aiWins = Number(localStorage.getItem('nexora_demo_wins') || 0), aiLosses = Number(localStorage.getItem('nexora_demo_losses') || 0);
function scan(){const ranked=aiMarkets.map(name=>({name,score:Math.round(58+Math.random()*38),trend:Math.random()>.48?'Rising':'Cooling',pulse:Math.round(20+Math.random()*78)})).sort((a,b)=>b.score-a.score);aiResult=ranked[0];ai$('#aiPick').textContent=`${aiResult.name} · ${aiResult.score}% activity`;ai$('#aiMeta').textContent=`${aiResult.trend} momentum · ${aiWins}W / ${aiLosses}L Demo`;ai$('#aiRanks').innerHTML=ranked.slice(0,5).map((item,index)=>`<button class="ai-rank" data-market="${item.name}"><span>${index+1}</span><b>${item.name}</b><i class="${item.trend==='Rising'?'up':'down'}">${item.trend}</i><em>${item.score}%</em></button>`).join('');document.querySelectorAll('.ai-rank').forEach(button=>button.onclick=()=>applyMarket(button.dataset.market));}
function applyMarket(name){ai$('#instrumentName').textContent=name;ai$('#aiPick').textContent=`${name} selected`;ai$('#aiSheet').classList.remove('open');toast(`${name} is ready to trade.`);}
function openScanner(){scan();ai$('#aiSheet').classList.add('open');}
ai$('#aiScan').onclick=openScanner;ai$('#aiGo').onclick=()=>aiResult?applyMarket(aiResult.name):openScanner();ai$('#aiClose').onclick=()=>ai$('#aiSheet').classList.remove('open');document.querySelector('#bottomAi').onclick=openScanner;
document.querySelectorAll('[data-ai]').forEach(button=>button.onclick=()=>{const type=button.dataset.ai;if(type==='watch')localStorage.setItem('nexora_ai_watch',aiResult?.name||'');if(type==='alert')localStorage.setItem('nexora_ai_alert',String(Date.now()));if(type==='journal'){const old=localStorage.getItem('nexora_journal')||'';localStorage.setItem('nexora_journal',`${old}\nAI scan: ${aiResult?.name||''}`)}if(type==='focus')document.body.classList.toggle('focus-mode');toast(`${button.textContent.trim()} updated.`);});
function flare(kind){const layer=ai$('#fxLayer');layer.innerHTML=Array.from({length:18},(_,index)=>`<i style="--x:${Math.random()*100}%;--d:${.5+Math.random()*.65}s;--c:${kind==='win'?'#37e2ac':'#ff6177'}"></i>`).join('');layer.className=`fx-layer show ${kind}`;setTimeout(()=>layer.className='fx-layer',1300)}
document.addEventListener('nexora:contract-outcome',event=>{if(event.detail.won){aiWins++;localStorage.setItem('nexora_demo_wins',aiWins);flare('win')}else{aiLosses++;localStorage.setItem('nexora_demo_losses',aiLosses);flare('loss')}scan();});
setInterval(scan,15000);scan();
