import 'dotenv/config';
import crypto from 'crypto';
import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { WebSocketServer } from 'ws';
import { db, migrate } from './db.js';
import { broker } from './broker.js';

const app = express();
const port = Number(process.env.PORT || 10000);
if (!process.env.JWT_SECRET) throw new Error('JWT_SECRET must be configured.');
// Render terminates TLS and forwards one trusted proxy hop to this service.
app.set('trust proxy', 1);
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: process.env.FRONTEND_ORIGIN?.split(',') || true, credentials: true }));
app.use('/api', rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: 'draft-7' }));
app.use(express.json({ verify: (req, res, buf) => { req.rawBody = buf; } }));
app.use(express.static('.'));
const issueToken = user => jwt.sign({ sub: user.id, email: user.email }, process.env.JWT_SECRET, { expiresIn: '1h', issuer: 'nexora.com', audience: 'nexora-app' });
function auth(req,res,next) { try { req.user = jwt.verify((req.headers.authorization || '').replace('Bearer ',''), process.env.JWT_SECRET, { issuer:'nexora.com', audience:'nexora-app' }); next(); } catch { res.status(401).json({ error:'Authentication required' }); } }
function reference(prefix='NXR') { return `${prefix}_${crypto.randomUUID().replaceAll('-','')}`; }
async function accountFor(client, userId, kind) { const { rows } = await client.query('SELECT * FROM accounts WHERE user_id=$1 AND kind=$2 FOR UPDATE',[userId,kind]); return rows[0]; }
async function paystack(path, body) { const r=await fetch(`https://api.paystack.co${path}`,{method:'POST',headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)}); const data=await r.json().catch(()=>({})); if(!r.ok||!data.status) { const error=new Error(data.message||'The payment provider rejected the M-Pesa request.'); error.status=r.status>=400&&r.status<500?422:502; throw error; } return data.data; }
async function verifyPaystack(reference) { const r=await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`,{headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`}}); const data=await r.json(); if(!r.ok||!data.status) throw new Error(data.message||'Paystack verification failed'); return data.data; }

app.get('/health', async (_,res)=>{try{await db.query('SELECT 1');res.json({ok:true,service:'nexora',database:'connected',time:new Date().toISOString()})}catch(error){res.status(503).json({ok:false,service:'nexora',database:'unavailable'})}});
app.get('/api/housika/config',auth,(_,res)=>{if(!process.env.PAYSTACK_PUBLIC_KEY)return res.status(503).json({error:'NEXORA Payments is not configured.'});res.json({publicKey:process.env.PAYSTACK_PUBLIC_KEY,currency:'KES',minimumAmount:650});});
app.post('/api/auth/signup', async (req,res,next)=>{ try { const email=String(req.body.email||'').trim().toLowerCase(), password=String(req.body.password||''); if(!/^\S+@\S+\.\S+$/.test(email)||password.length<4) return res.status(400).json({error:'Use a valid email and a password of at least 4 characters.'}); const hash=await bcrypt.hash(password,12); const {rows:[user]}=await db.query('INSERT INTO users(email,password_hash) VALUES($1,$2) RETURNING id,email',[email,hash]); await db.query("INSERT INTO accounts(user_id,kind,balance) VALUES($1,'demo',10000),($1,'real',0)",[user.id]); res.status(201).json({token:issueToken(user),user}); }catch(e){ if(e.code==='23505') return res.status(409).json({error:'An account with this email exists.'}); next(e); }});
app.post('/api/auth/signin', async(req,res,next)=>{try{const {rows:[user]}=await db.query('SELECT * FROM users WHERE email=$1',[String(req.body.email||'').trim().toLowerCase()]);if(!user||!await bcrypt.compare(String(req.body.password||''),user.password_hash))return res.status(401).json({error:'Invalid email or password.'});res.json({token:issueToken(user),user:{id:user.id,email:user.email}})}catch(e){next(e)}});
app.get('/api/accounts',auth,async(req,res,next)=>{try{const {rows}=await db.query('SELECT id,kind,currency,balance FROM accounts WHERE user_id=$1 ORDER BY kind',[req.user.sub]);res.json(rows)}catch(e){next(e)}});
app.get('/api/workspace',auth,async(req,res,next)=>{try{const [accounts,activity,preferences]=await Promise.all([db.query('SELECT kind,currency,balance FROM accounts WHERE user_id=$1 ORDER BY kind',[req.user.sub]),db.query('SELECT contract_type AS type,result,amount,label,created_at AS at FROM demo_trade_activity WHERE user_id=$1 ORDER BY created_at DESC LIMIT 30',[req.user.sub]),db.query('SELECT preferences FROM user_preferences WHERE user_id=$1',[req.user.sub])]);res.json({accounts:accounts.rows,activity:activity.rows,preferences:preferences.rows[0]?.preferences||{}})}catch(e){next(e)}});
app.patch('/api/demo/balance',auth,async(req,res,next)=>{try{const action=String(req.body.action||''),amount=Number(req.body.amount||0);if(action==='reset'){const {rows:[account]}=await db.query("UPDATE accounts SET balance=10000 WHERE user_id=$1 AND kind='demo' RETURNING balance",[req.user.sub]);return res.json({balance:Number(account.balance)})}if(!['debit','credit'].includes(action)||!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Invalid demo balance update.'});const delta=action==='debit'?-amount:amount;const {rows:[account]}=await db.query("UPDATE accounts SET balance=GREATEST(0,balance+$1) WHERE user_id=$2 AND kind='demo' RETURNING balance",[delta,req.user.sub]);res.json({balance:Number(account.balance)})}catch(e){next(e)}});
app.post('/api/demo/activity',auth,async(req,res,next)=>{try{const type=String(req.body.type||'Trade').slice(0,40),result=String(req.body.result||'open').slice(0,20),amount=Number(req.body.amount),label=String(req.body.label||'').slice(0,100);if(!Number.isFinite(amount)||amount<0)return res.status(400).json({error:'Invalid activity amount.'});const {rows:[activity]}=await db.query('INSERT INTO demo_trade_activity(user_id,contract_type,result,amount,label) VALUES($1,$2,$3,$4,$5) RETURNING contract_type AS type,result,amount,label,created_at AS at',[req.user.sub,type,result,amount,label]);res.status(201).json(activity)}catch(e){next(e)}});
app.put('/api/preferences',auth,async(req,res,next)=>{try{const preferences=req.body.preferences&&typeof req.body.preferences==='object'?req.body.preferences:{};await db.query('INSERT INTO user_preferences(user_id,preferences,updated_at) VALUES($1,$2,now()) ON CONFLICT(user_id) DO UPDATE SET preferences=EXCLUDED.preferences,updated_at=now()',[req.user.sub,preferences]);res.sendStatus(204)}catch(e){next(e)}});
app.get('/api/profile',auth,async(req,res,next)=>{try{const {rows:[user]}=await db.query('SELECT id,email,display_name,withdrawal_method,withdrawal_destination FROM users WHERE id=$1',[req.user.sub]);res.json(user)}catch(e){next(e)}});
app.patch('/api/profile',auth,async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),displayName=String(req.body.displayName||'').trim();if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Enter a valid email address.'});const {rows:[user]}=await db.query('UPDATE users SET email=$1,display_name=$2 WHERE id=$3 RETURNING id,email,display_name,withdrawal_method,withdrawal_destination',[email,displayName||null,req.user.sub]);res.json({user,token:issueToken(user)})}catch(e){if(e.code==='23505')return res.status(409).json({error:'That email address is already in use.'});next(e)}});
app.patch('/api/profile/withdrawal-destination',auth,async(req,res,next)=>{try{const method=String(req.body.method||''),destination=String(req.body.destination||'').trim();if(!['mpesa','trc20'].includes(method)||!destination)return res.status(400).json({error:'Enter a valid withdrawal destination.'});const {rows:[user]}=await db.query('UPDATE users SET withdrawal_method=$1,withdrawal_destination=$2 WHERE id=$3 RETURNING id,email,display_name,withdrawal_method,withdrawal_destination',[method,destination,req.user.sub]);res.json(user)}catch(e){next(e)}});
app.delete('/api/profile',auth,async(req,res,next)=>{try{const password=String(req.body.password||'');const {rows:[user]}=await db.query('SELECT password_hash FROM users WHERE id=$1',[req.user.sub]);if(!user||!await bcrypt.compare(password,user.password_hash))return res.status(401).json({error:'Password confirmation is incorrect.'});await db.query('DELETE FROM users WHERE id=$1',[req.user.sub]);res.sendStatus(204)}catch(e){next(e)}});

app.post('/api/housika/deposit-intent',auth,async(req,res,next)=>{try{const amountKes=Number(req.body.amountKes),checkoutEmail=String(process.env.PAYSTACK_PAYMENT_EMAIL||'').trim();if(!Number.isFinite(amountKes)||amountKes<650)return res.status(400).json({error:'Minimum deposit is KSh 650.'});if(!/^\S+@\S+\.\S+$/.test(checkoutEmail))return res.status(503).json({error:'Payments are not configured. Set PAYSTACK_PAYMENT_EMAIL on the server.'});const client=await db.connect();try{await client.query('BEGIN');const acct=await accountFor(client,req.user.sub,'real');const ref=reference('HSK');await client.query("INSERT INTO payment_events(reference,user_id,account_id,direction,amount) VALUES($1,$2,$3,'deposit',$4)",[ref,req.user.sub,acct.id,amountKes/130]);await client.query('COMMIT');res.status(201).json({reference:ref,amountKes,checkoutEmail});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}catch(e){next(e)}});
app.post('/api/housika/verify-deposit',auth,async(req,res,next)=>{try{const reference=String(req.body.reference||'');if(!reference)return res.status(400).json({error:'Payment reference is required.'});const paid=await verifyPaystack(reference);if(paid.status!=='success')return res.status(409).json({error:'Payment is not complete.'});const client=await db.connect();try{await client.query('BEGIN');const {rows:[payment]}=await client.query("UPDATE payment_events SET status='settled',provider_payload=$1,settled_at=now() WHERE reference=$2 AND user_id=$3 AND direction='deposit' AND status='pending' RETURNING *",[paid,reference,req.user.sub]);if(!payment){await client.query('ROLLBACK');return res.status(409).json({error:'This payment was already processed or is invalid.'});}if(Math.round(Number(payment.amount)*13000)!==Number(paid.amount)){await client.query('ROLLBACK');return res.status(400).json({error:'Payment amount does not match the deposit request.'});}await client.query('UPDATE accounts SET balance=balance+$1 WHERE id=$2',[payment.amount,payment.account_id]);await client.query('COMMIT');res.json({status:'SUCCESS',balanceCredited:payment.amount});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}catch(e){next(e)}});
app.post('/api/payments/withdraw',auth,(_,res)=>res.status(403).json({error:'Withdrawals are disabled pending operator approval.'}));
app.post('/api/withdrawal-requests',auth,async(req,res,next)=>{try{const amount=Number(req.body.amount),method=String(req.body.method||''),destination=String(req.body.destination||'').trim();if(!Number.isFinite(amount)||amount<10||!['mpesa','trc20'].includes(method)||!destination)return res.status(400).json({error:'Minimum withdrawal is $10. Enter a valid destination.'});const {rows:[request]}=await db.query('INSERT INTO withdrawal_requests(user_id,amount,method,destination) VALUES($1,$2,$3,$4) RETURNING id,status,created_at',[req.user.sub,amount,method,destination]);res.status(202).json({request});}catch(e){next(e)}});
app.post('/api/payments/paystack/webhook',async(req,res,next)=>{try{const signature=req.get('x-paystack-signature')||'';const valid=crypto.createHmac('sha512',process.env.PAYSTACK_WEBHOOK_SECRET||process.env.PAYSTACK_SECRET_KEY).update(req.rawBody).digest('hex');const supplied=Buffer.from(signature), expected=Buffer.from(valid);if(supplied.length!==expected.length||!crypto.timingSafeEqual(supplied,expected))return res.status(401).send('Invalid signature');const event=req.body;const eventId=`${event.event}:${event.data?.reference||event.data?.id}`;const client=await db.connect();try{await client.query('BEGIN');const exists=await client.query('SELECT 1 FROM webhook_events WHERE event_id=$1',[eventId]);if(exists.rowCount){await client.query('ROLLBACK');return res.sendStatus(200)}await client.query('INSERT INTO webhook_events(event_id,payload) VALUES($1,$2)',[eventId,event]);if(event.event==='charge.success'){const ref=event.data.reference;const {rows:[payment]}=await client.query("UPDATE payment_events SET status='settled',provider_payload=$1,settled_at=now() WHERE reference=$2 AND direction='deposit' AND status='pending' RETURNING *",[event.data,ref]);if(payment)await client.query('UPDATE accounts SET balance=balance+$1 WHERE id=$2',[payment.amount,payment.account_id]);}if(event.event==='transfer.failed'||event.event==='transfer.reversed'){const ref=event.data.reference;const {rows:[payment]}=await client.query("UPDATE payment_events SET status='reversed',provider_payload=$1 WHERE reference=$2 AND direction='withdrawal' AND status='pending' RETURNING *",[event.data,ref]);if(payment)await client.query('UPDATE accounts SET balance=balance+$1 WHERE id=$2',[payment.amount,payment.account_id]);}await client.query('COMMIT');res.sendStatus(200)}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}catch(e){next(e)}});
app.post('/api/orders',auth,async(req,res,next)=>{try{const {symbol,side,orderType='market',amount,accountKind='real'}=req.body;if(!['buy','sell'].includes(side)||!symbol||!Number.isFinite(Number(amount))||Number(amount)<=0)return res.status(400).json({error:'Invalid order.'});const {rows:[account]}=await db.query('SELECT * FROM accounts WHERE user_id=$1 AND kind=$2',[req.user.sub,accountKind]);if(!account)return res.status(404).json({error:'Account not found.'});const result=await broker.placeOrder({symbol,side,orderType,amount:Number(amount),accountId:account.id});const {rows:[order]}=await db.query('INSERT INTO orders(user_id,account_id,broker_order_id,symbol,side,order_type,amount,status,provider_payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[req.user.sub,account.id,String(result.id||result.orderId||''),symbol,side,orderType,amount,result.status||'submitted',result]);res.status(201).json(order)}catch(e){next(e)}});
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({error:err.status?err.message:'Server error',requestId:reference('ERR')});});
async function start() {
  await migrate();
  const server = app.listen(port, () => console.log(`NEXORA listening on ${port}`));
  const wss = new WebSocketServer({ server, path:'/ws/market' });
  wss.on('connection', ws => ws.send(JSON.stringify({type:'connection',status:'connected',message:'Connect your licensed market feed in broker.js'})));
}
start().catch(error => { console.error('NEXORA failed to start:', error.message); process.exit(1); });
