import 'dotenv/config';
import crypto from 'crypto';
import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { WebSocketServer } from 'ws';
import { db, migrate } from './db.js';
import { broker } from './broker.js';

const app = express();
const port = Number(process.env.PORT || 10000);
if (!process.env.JWT_SECRET) throw new Error('JWT_SECRET must be configured.');
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: process.env.FRONTEND_ORIGIN?.split(',') || true, credentials: true }));
app.use('/api', rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: 'draft-7' }));
app.use(express.json({ verify: (req, res, buf) => { req.rawBody = buf; } }));
app.use(express.static('.'));
const issueToken = user => jwt.sign({ sub: user.id, email: user.email }, process.env.JWT_SECRET, { expiresIn: '8h', issuer: 'nexora.com', audience: 'nexora-app' });
function auth(req,res,next) { try { req.user = jwt.verify((req.headers.authorization || '').replace('Bearer ',''), process.env.JWT_SECRET, { issuer:'nexora.com', audience:'nexora-app' }); next(); } catch { res.status(401).json({ error:'Authentication required' }); } }
function reference(prefix='NXR') { return `${prefix}_${crypto.randomUUID().replaceAll('-','')}`; }
async function accountFor(client, userId, kind) { const { rows } = await client.query('SELECT * FROM accounts WHERE user_id=$1 AND kind=$2 FOR UPDATE',[userId,kind]); return rows[0]; }
async function paystack(path, body) { const r=await fetch(`https://api.paystack.co${path}`,{method:'POST',headers:{Authorization:`Bearer ${process.env.PAYSTACK_SECRET_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)}); const data=await r.json(); if(!r.ok||!data.status) throw new Error(data.message||'Paystack request failed'); return data.data; }

app.get('/health', (_,res)=>res.json({ ok:true, service:'nexora', time:new Date().toISOString() }));
app.post('/api/auth/signup', async (req,res,next)=>{ try { const email=String(req.body.email||'').trim().toLowerCase(), password=String(req.body.password||''); if(!/^\S+@\S+\.\S+$/.test(email)||password.length<12) return res.status(400).json({error:'Use a valid email and a password of at least 12 characters.'}); const hash=await bcrypt.hash(password,12); const {rows:[user]}=await db.query('INSERT INTO users(email,password_hash) VALUES($1,$2) RETURNING id,email',[email,hash]); await db.query("INSERT INTO accounts(user_id,kind,balance) VALUES($1,'demo',10000),($1,'real',0)",[user.id]); res.status(201).json({token:issueToken(user),user}); }catch(e){ if(e.code==='23505') return res.status(409).json({error:'An account with this email exists.'}); next(e); }});
app.post('/api/auth/signin', async(req,res,next)=>{try{const {rows:[user]}=await db.query('SELECT * FROM users WHERE email=$1',[String(req.body.email||'').trim().toLowerCase()]);if(!user||!await bcrypt.compare(String(req.body.password||''),user.password_hash))return res.status(401).json({error:'Invalid email or password.'});res.json({token:issueToken(user),user:{id:user.id,email:user.email}})}catch(e){next(e)}});
app.get('/api/accounts',auth,async(req,res,next)=>{try{const {rows}=await db.query('SELECT id,kind,currency,balance FROM accounts WHERE user_id=$1 ORDER BY kind',[req.user.sub]);res.json(rows)}catch(e){next(e)}});

app.post('/api/payments/deposit/initialize',auth,async(req,res,next)=>{try{const amount=Number(req.body.amount),email=req.user.email;if(!Number.isFinite(amount)||amount<5)return res.status(400).json({error:'Minimum deposit is USD 5.'});const client=await db.connect();try{await client.query('BEGIN');const acct=await accountFor(client,req.user.sub,'real');const ref=reference('DEP');await client.query("INSERT INTO payment_events(reference,user_id,account_id,direction,amount) VALUES($1,$2,$3,'deposit',$4)",[ref,req.user.sub,acct.id,amount]);await client.query('COMMIT');const data=await paystack('/transaction/initialize',{email,amount:Math.round(amount*100),reference:ref,callback_url:process.env.PAYSTACK_CALLBACK_URL,metadata:{user_id:req.user.sub,account_id:acct.id}});res.json({reference:ref,authorizationUrl:data.authorization_url,accessCode:data.access_code});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}catch(e){next(e)}});
app.post('/api/payments/withdraw',auth,async(req,res,next)=>{try{const amount=Number(req.body.amount),recipientCode=String(req.body.recipientCode||'');if(!Number.isFinite(amount)||amount<10||!recipientCode)return res.status(400).json({error:'Amount and verified Paystack recipient code are required.'});const client=await db.connect();try{await client.query('BEGIN');const {rows:[acct]}=await client.query("SELECT * FROM accounts WHERE user_id=$1 AND kind='real' FOR UPDATE",[req.user.sub]);if(Number(acct.balance)<amount){await client.query('ROLLBACK');return res.status(400).json({error:'Insufficient available balance.'})}const ref=reference('WDL');await client.query('UPDATE accounts SET balance=balance-$1 WHERE id=$2',[amount,acct.id]);await client.query("INSERT INTO payment_events(reference,user_id,account_id,direction,amount) VALUES($1,$2,$3,'withdrawal',$4)",[ref,req.user.sub,acct.id,amount]);await client.query('COMMIT');const transfer=await paystack('/transfer',{source:'balance',amount:Math.round(amount*100),recipient:recipientCode,reason:'NEXORA withdrawal',reference:ref});res.status(202).json({reference:ref,status:transfer.status});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}catch(e){next(e)}});
app.post('/api/payments/paystack/webhook',async(req,res,next)=>{try{const signature=req.get('x-paystack-signature')||'';const valid=crypto.createHmac('sha512',process.env.PAYSTACK_WEBHOOK_SECRET||process.env.PAYSTACK_SECRET_KEY).update(req.rawBody).digest('hex');const supplied=Buffer.from(signature), expected=Buffer.from(valid);if(supplied.length!==expected.length||!crypto.timingSafeEqual(supplied,expected))return res.status(401).send('Invalid signature');const event=req.body;const eventId=`${event.event}:${event.data?.reference||event.data?.id}`;const client=await db.connect();try{await client.query('BEGIN');const exists=await client.query('SELECT 1 FROM webhook_events WHERE event_id=$1',[eventId]);if(exists.rowCount){await client.query('ROLLBACK');return res.sendStatus(200)}await client.query('INSERT INTO webhook_events(event_id,payload) VALUES($1,$2)',[eventId,event]);if(event.event==='charge.success'){const ref=event.data.reference;const {rows:[payment]}=await client.query("UPDATE payment_events SET status='settled',provider_payload=$1,settled_at=now() WHERE reference=$2 AND direction='deposit' AND status='pending' RETURNING *",[event.data,ref]);if(payment)await client.query('UPDATE accounts SET balance=balance+$1 WHERE id=$2',[payment.amount,payment.account_id]);}if(event.event==='transfer.failed'||event.event==='transfer.reversed'){const ref=event.data.reference;const {rows:[payment]}=await client.query("UPDATE payment_events SET status='reversed',provider_payload=$1 WHERE reference=$2 AND direction='withdrawal' AND status='pending' RETURNING *",[event.data,ref]);if(payment)await client.query('UPDATE accounts SET balance=balance+$1 WHERE id=$2',[payment.amount,payment.account_id]);}await client.query('COMMIT');res.sendStatus(200)}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}catch(e){next(e)}});
app.post('/api/orders',auth,async(req,res,next)=>{try{const {symbol,side,orderType='market',amount,accountKind='real'}=req.body;if(!['buy','sell'].includes(side)||!symbol||!Number.isFinite(Number(amount))||Number(amount)<=0)return res.status(400).json({error:'Invalid order.'});const {rows:[account]}=await db.query('SELECT * FROM accounts WHERE user_id=$1 AND kind=$2',[req.user.sub,accountKind]);if(!account)return res.status(404).json({error:'Account not found.'});const result=await broker.placeOrder({symbol,side,orderType,amount:Number(amount),accountId:account.id});const {rows:[order]}=await db.query('INSERT INTO orders(user_id,account_id,broker_order_id,symbol,side,order_type,amount,status,provider_payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[req.user.sub,account.id,String(result.id||result.orderId||''),symbol,side,orderType,amount,result.status||'submitted',result]);res.status(201).json(order)}catch(e){next(e)}});
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({error:err.status?err.message:'Server error'});});
async function start() {
  await migrate();
  const server = app.listen(port, () => console.log(`NEXORA listening on ${port}`));
  const wss = new WebSocketServer({ server, path:'/ws/market' });
  wss.on('connection', ws => ws.send(JSON.stringify({type:'connection',status:'connected',message:'Connect your licensed market feed in broker.js'})));
}
start().catch(error => { console.error('NEXORA failed to start:', error.message); process.exit(1); });
