const s$ = selector => document.querySelector(selector);
const userToken = () => localStorage.getItem('nexora_token');
if (!userToken()) location.replace('index.html');
const elitePrefs = ['Theme profile','High contrast','Reduced motion','Focus mode','Price alerts','Trade sounds','Private journal','Daily Demo limit','AI auto-scan','Market favorites','Default candles','Default line','Quick stakes','Demo cash-out','Win/loss insights','Touch feedback','Session timer','Break reminder','Connection health','Journal export','Save chart zoom','Large text','Compact trading','Scanner alerts','Setup alerts','Contract limit','Loss cooldown','Payout warning','Latency meter','Status ribbon'];
const pageMeta = {home:['Your NEXORA space','Account, wallet, and workspace controls in one place.'],profile:['Profile settings','Update the information connected to your NEXORA account.'],wallet:['Wallet settings','Manage payout details and open the secure cashier.'],workspace:['Elite controls','30 workspace controls are ready to personalize your experience.'],journal:['Trade journal','Private notes stored only on this device.'],help:['Help & learning','Resources for practising responsibly and learning the workspace.']};
function note(message){const element=s$('#status');if(element)element.textContent=message;}
function signOut(){localStorage.removeItem('nexora_token');localStorage.removeItem('nexora_user');location.replace('index.html');}
async function profile(){const response=await fetch('/api/profile',{headers:{Authorization:`Bearer ${userToken()}`}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not load profile.');return data;}
const sections={
 home:async()=>{const saved=JSON.parse(localStorage.getItem('nexora_user')||'{}');return `<div class="settings-card"><h2>Welcome${saved.email?`, ${saved.email.split('@')[0]}`:''}</h2><p>Everything important is grouped here. Choose a card to open its active controls.</p><div class="quick-row"><button data-go="wallet">Deposit & wallet</button><button data-go="workspace">AI & elite controls</button><button data-go="journal">Add a trade note</button></div></div><div class="overview-grid"><button data-go="profile"><i>◉</i><b>Profile</b><small>Name, email & account access</small></button><button data-go="wallet"><i>◈</i><b>Wallet</b><small>Deposit, withdrawals & payout route</small></button><button data-go="workspace"><i>✦</i><b>Elite controls</b><small>30 personal workspace preferences</small></button><button data-go="journal"><i>▤</i><b>Trade journal</b><small>Capture private trade notes</small></button><button data-go="help"><i>?</i><b>Learn</b><small>Binary contracts and risk guidance</small></button><button id="overviewTrade"><i>↗</i><b>Trade now</b><small>Return to live workspace</small></button></div>`;},
 profile:async()=>{const user=await profile();return `<div class="settings-card"><h2>Profile details</h2><p>Your information stays attached to your NEXORA account.</p><label>Display name<input id="name" value="${user.display_name||''}" placeholder="Your name"></label><label>Email<input id="email" type="email" value="${user.email||''}"></label><button id="saveProfile">Save profile</button><p class="status" id="status"></p></div><div class="settings-card"><h2>Account access</h2><p>Signing out ends dashboard access on this device. Deleting is permanent and requires your password.</p><button class="danger" id="deleteAccount">Delete account</button></div>`;},
 wallet:async()=>{const user=await profile();return `<div class="settings-card"><h2>Withdrawal destination</h2><p>Configure the destination used when you request a withdrawal.</p><label>Method<select id="method"><option value="mpesa">M-Pesa</option><option value="trc20">USDT TRC20</option></select></label><label>Destination<input id="destination" value="${user.withdrawal_destination||''}" placeholder="M-Pesa number or TRC20 address"></label><button id="saveWallet">Save destination</button><button class="secondary" id="openCashier">Open cashier</button><p class="status" id="status"></p></div>`;},
 workspace:async()=>`<div class="settings-card"><h2>30 elite controls</h2><p>Tap any control to activate its local preference. Live execution capabilities still require a licensed provider connection.</p><div class="tool-prefs">${elitePrefs.map((label,index)=>`<button data-pref="elite-${index+1}">${String(index+1).padStart(2,'0')} · ${label}</button>`).join('')}</div><p class="status" id="status"></p></div>`,
 journal:async()=>`<div class="settings-card"><h2>Private trade journal</h2><p>Record your entry reasoning, outcomes, or rules. This stays on this device.</p><textarea class="journal-box" id="journalText" placeholder="Write a note…">${localStorage.getItem('nexora_journal')||''}</textarea><button id="saveJournal">Save journal</button><button class="secondary" id="exportJournal">Export</button><p class="status" id="status"></p></div>`,
 help:async()=>`<div class="settings-card"><h2>Learn before you trade</h2><p>Explore contract basics, Demo practice, and responsible-trading guidance.</p><button id="openLearn">Open NEXORA Learn</button><button class="secondary" id="returnTrading">Return to trading</button></div><div class="settings-card"><h2>Connection status</h2><p><b style="color:#55ddb2">● Workspace online</b><br>Market display is simulated until a licensed market-data provider is connected.</p></div>`
};
async function load(section){try{const [title,subtitle]=pageMeta[section];s$('#settingsTitle').textContent=title;s$('#settingsSubtitle').textContent=subtitle;s$('#settingsBody').innerHTML=await sections[section]();document.querySelectorAll('[data-section]').forEach(button=>button.classList.toggle('active',button.dataset.section===section));bind(section);}catch(error){s$('#settingsBody').innerHTML=`<div class="settings-card"><h2>Unable to load</h2><p>${error.message}</p><button id="retryLoad">Try again</button></div>`;s$('#retryLoad')?.addEventListener('click',()=>load(section));}}
function bind(section){document.querySelectorAll('[data-go]').forEach(button=>button.onclick=()=>load(button.dataset.go));s$('#overviewTrade')?.addEventListener('click',()=>location.href='binary.html');if(section==='profile'){s$('#saveProfile').onclick=async()=>{const response=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${userToken()}`},body:JSON.stringify({displayName:s$('#name').value,email:s$('#email').value})});const data=await response.json();if(!response.ok)return note(data.error);localStorage.setItem('nexora_token',data.token);localStorage.setItem('nexora_user',JSON.stringify(data.user));note('Profile saved.');};s$('#deleteAccount').onclick=async()=>{const password=prompt('Enter your password to permanently delete this account.');if(!password)return;const response=await fetch('/api/profile',{method:'DELETE',headers:{'Content-Type':'application/json',Authorization:`Bearer ${userToken()}`},body:JSON.stringify({password})});if(response.ok)signOut();else note((await response.json()).error||'Could not delete account.');};}if(section==='wallet'){s$('#method').value=(JSON.parse(localStorage.getItem('nexora_profile')||'{}').withdrawal_method||'mpesa');s$('#saveWallet').onclick=async()=>{const response=await fetch('/api/profile/withdrawal-destination',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${userToken()}`},body:JSON.stringify({method:s$('#method').value,destination:s$('#destination').value})});const data=await response.json();if(response.ok)localStorage.setItem('nexora_profile',JSON.stringify(data));note(response.ok?'Withdrawal destination saved.':data.error);};s$('#openCashier').onclick=()=>{sessionStorage.setItem('nexora_internal_navigation','settings');location.href='binary.html';};}if(section==='workspace')document.querySelectorAll('[data-pref]').forEach(button=>button.onclick=()=>{localStorage.setItem(`nexora_pref_${button.dataset.pref}`,String(Date.now()));button.classList.add('active');note(`${button.textContent} enabled.`);});if(section==='journal'){s$('#saveJournal').onclick=()=>{localStorage.setItem('nexora_journal',s$('#journalText').value);note('Journal saved on this device.');};s$('#exportJournal').onclick=()=>{const blob=new Blob([s$('#journalText').value||'No journal notes yet.'],{type:'text/plain'});const link=Object.assign(document.createElement('a'),{href:URL.createObjectURL(blob),download:'nexora-trade-journal.txt'});link.click();URL.revokeObjectURL(link.href);note('Journal export started.');};}if(section==='help'){s$('#openLearn').onclick=()=>location.href='learn.html';s$('#returnTrading').onclick=()=>location.href='binary.html';}}
document.querySelectorAll('[data-section]').forEach(button=>button.onclick=()=>load(button.dataset.section));s$('#returnTrade').onclick=()=>location.href='binary.html';s$('#closeSettings').onclick=()=>location.href='binary.html';s$('#settingsSignOut').onclick=signOut;s$('#menuTheme').onclick=()=>{document.body.classList.toggle('menu-light');};const saved=JSON.parse(localStorage.getItem('nexora_user')||'{}');s$('#sideUser').textContent=saved.email||'Signed-in account';load('home');
